backend/urls.py
from django.urls import path
from .views import *

app_name = 'my'

urlpatterns = [
    path('', redirect_check, name='redirect'),
    path('book/', BookListUploaded.as_view(), name='book-list'),
    path('book/check/', upload_check, name='book-check'),
    path('book/upload/', UploadBook.as_view(), name='upload-a-book'),
    path('book/<slug:link>/', BookDetail.as_view(), name='book-detail'),
    path('book/<slug:link>/update', UpdateBook.as_view(), name='book-update'),
]

e_libs/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my/', include('backend.urls', namespace='my')),
    path('profile/', include('members.urls', namespace='profile')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('', include('read.urls', namespace='read')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

members/urls.py
from django.urls import path
from .views import *

app_name = 'profile'

urlpatterns = [
    path('', ProfileHome.as_view(), name='home'),
    path('create/', CreateProfile.as_view(), name='create-profile'),
    path('<str:pk>/update/', UpdateProfile.as_view(), name='update-profile'),
]

read/urls.py
from django.urls import path
from .views import *

app_name = 'read'

urlpatterns = [
    path('', AllBooksList.as_view(), name='book'),
    path('book/', AllBookList.as_view(), name='book-list'),
    # path('<str:cats>/', CategorySearch, name='category'),
    path('<slug:link>/', BookDetailView.as_view(), name='detail'),
    path('<slug:link>/comment/', AddComment.as_view(), name='add-comment'),
]

members/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name='phone')
    name = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user) + ' as ' + self.name

members/forms.py
from django import forms
from .models import UserProfile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('name', 'phone', )

members/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy as rl
from django.views.generic import *
from .forms import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect


class ProfileHome(TemplateView):
    template_name = 'member/main.html'
    # model = UserProfile

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileHome, self).get_context_data(*args, **kwargs)
        userprofile = UserProfile.objects.get(user_id=self.request.user.id)
        print(userprofile)

        context['userprofile'] = userprofile
        return context

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(ProfileHome, self).dispatch(request, *args, **kwargs)


class CreateProfile(CreateView):
    model = UserProfile
    template_name = 'member/create.html'
    form_class = CreateProfileForm
    success_url = rl('profile:home')

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        a = super(CreateProfile, self).form_valid(form)
        b = HttpResponseRedirect(self.get_success_url())
        return a and b

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(CreateProfile, self).dispatch(request, *args, **kwargs)


class UpdateProfile(UpdateView):
    model = UserProfile
    template_name = 'member/update.html'
    form_class = CreateProfileForm
    success_url = rl('profile:home')

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(UpdateProfile, self).dispatch(request, *args, **kwargs)

members/templates/member/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

        <title>{% block title %} {% endblock %}</title>
    </head>
    <body>

    {% block content %}
    {% endblock %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    </body>
</html>

members/templates/member/create.html
{% extends 'member/base.html' %}

{% block title %}Main Menu{% endblock %}

{% block content %}

    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            {{ form | crispy}}
            <div class="form-group">
                <button class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>

{% endblock %}

members/templates/member/main.html
{% extends 'member/base.html' %}

{% block title %}Main Menu{% endblock %}

{% block content %}

<div class="jumbotron">
    <div class="container mt-3 ">
        <h1 class="display-4">Hello, {{ userprofile.name }}</h1>
        <p class="lead">Here this Your Number : {{ userprofile.phone }}.</p>
        <hr class="my-4">
        <div class="d-flex">
            <form action="{% url 'my:upload-a-book' %}" class="mx-3">
                <button class="btn btn-lg btn-primary">Upload A Book Now</button>
            </form>
            <form action="{% url 'profile:update-profile' userprofile.pk  %}">
                <button class="btn btn-primary btn-lg">Update Data</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

members/templates/member/update.html
{% extends 'member/base.html' %}

{% block title %}Update Profile{% endblock %}

{% block content %}

    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            {{ form | crispy}}
            <div class="form-group">
                <button class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>

{% endblock %}