e_libs/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my/', include('backend.urls', namespace='my')),
    path('profile/', include('members.urls', namespace='profile')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('', include('read.urls', namespace='read')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

read/urls.py
from django.urls import path
from .views import *

app_name = 'read'

urlpatterns = [
    path('', AllBooksList.as_view(), name='book'),
    path('book/', AllBookList.as_view(), name='book-list'),
    # path('<str:cats>/', CategorySearch, name='category'),
    path('<slug:link>/', BookDetailView.as_view(), name='detail'),
    path('<slug:link>/comment/', AddComment.as_view(), name='add-comment'),
]

read/models.py
from django.db import models
from ckeditor.fields import RichTextField
from backend.models import Book
from django.contrib.auth.models import User


class Comment(models.Model):
    book = models.ForeignKey(Book, related_name='comment', on_delete=models.CASCADE)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(null=True, blank=True, config_name='comment')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.book.title, self.name)

read/forms.py
from django import forms
from .models import Comment


class AddCommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )

read/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import *
from backend.models import Book, Category
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import *
from django.db.models import Count, Q
from members.models import UserProfile

link = 'link'


class AllBooksList(TemplateView):
    template_name = 'read/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(AllBooksList, self).get_context_data(*args, **kwargs)
        fav_book = Book.objects.all().order_by('rating')[:6]
        book_total = Book.objects.all().count()
        member = User.objects.all().count()
        category = Category.objects.all().count()

        context['fav_books'] = fav_book
        context['book_total'] = book_total
        context['member'] = member
        context['category'] = category
        return context


# def like_view(request, pk):
#     book = get_object_or_404(Book, id=request.POST.get('book_id'))
#     current_score = book.current_rate()
#     rated = False
#     # Delete rating the book
#     if book.user_rating.filter(id=request.user.id).exists():
#         pass
#     else:
#         book.user_rating.add(request.user)
#         current_score += int(request.POST.get('rating_point'))
#         rated = True
#
#     return HttpResponseRedirect(reverse('book-detail', args=[str(pk)]))


class BookDetailView(DetailView):
    template_name = 'read/details.html'
    # template_name = 'read/base1.html'
    query_pk_and_slug = True
    slug_url_kwarg = link
    slug_field = link
    model = Book

    def get_context_data(self, *args, **kwargs):
        context = super(BookDetailView, self).get_context_data(*args, **kwargs)
        category = Category.objects.all()
        tile = Book.objects.get(link=self.kwargs['link'])
        profile_ = UserProfile.objects.filter(user_id=Book.objects.get(pk=tile.pk).uploader)
        if profile_ is not None:
            profile = UserProfile.objects.get(user_id=Book.objects.get(pk=tile.pk).uploader)
            context['profile'] = profile
        else:
            pass

        context['category'] = category
        return context


class AddComment(CreateView):
    model = Comment
    form_class = AddCommentForms
    template_name = 'read/add-comment.html'
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link

    def get_success_url(self):
        return reverse('read:detail', args=[str(self.kwargs[link])])

    def form_valid(self, form):
        pk = Book.objects.get(link=self.kwargs[link])
        form.instance.book_id = pk.pk
        form.instance.name_id = self.request.user.id
        return super().form_valid(form) and HttpResponseRedirect(self.get_success_url())

    @method_decorator(login_required(login_url="/accounts/login/"))
    def dispatch(self, request, *args, **kwargs):
        return super(AddComment, self).dispatch(request, *args, **kwargs)

# def CategorySearch(req, cats):
#     cate = Book.objects.filter(category=cats.replace('-', ' '))
#     con = {
#         'cats': cats.replace('-', ' ').title(),
#         'category_posts': cate
#     }
#     return render(req, '', con)


class AllBookList(ListView):
    model = Book
    template_name = 'read/list.html'
    paginate_by = 6
    ordering = ['-pk']

    def get_queryset(self):
        qq = self.request.GET.get('q')
        if qq is not None:
            object_list = Book.objects.filter(
                Q(title__icontains=qq) | Q(link__icontains=qq) | Q(description__icontains=qq)
            ).order_by('-pk')
        else:
            object_list = Book.objects.all().order_by('-pk')

        return object_list

    def get_context_data(self, *args, **kwargs):
        context = super(AllBookList, self).get_context_data(*args, **kwargs)
        fav_book = Book.objects.all().order_by('rating')[:4]
        new_book = Book.objects.all().order_by('-pk')[:1]
        cat = Category.objects.all().order_by('-pk')[:3]

        context['category'] = cat
        context['new_book'] = new_book
        context['fav_books'] = fav_book
        return context

read/templates/read/add-comment.html
{% extends 'base.html' %}

{% block title %} Comment {% endblock %}

{% block body %}
    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            {{form.media}}
            <div class="form-group">
                {{form | crispy}}
            </div>
            <div class="form-group">
                <button class="btn btn-primary"> Save </button>
            </div>
        </form>
    </div>
{% endblock %}

read/templates/read/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/book/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="/static/book/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    {% block head %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-white portfolio-navbar gradient">
        <div class="container"><a class="navbar-brand logo" href="/my/book/">E Libs</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navbarNav"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="/my/book/upload/">Upload A Book</a></li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="/accounts/logout/">LogOut</a>
                        {% else %}
                        <a class="nav-link" href="/accounts/login/">Login</a>
                        {% endif %}
                    </li>
                    <li class="nav-item"><a class="nav-link active" href="project-page.html">Project Page</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <main class="page project-page">
        {% block body %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="container">
            <div class="links"><a href="#">About me</a><a href="#">Contact me</a><a href="#">Projects</a></div>
            <div class="social-icons"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-instagram-outline"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a></div>
        </div>
    </footer>
    <script src="/static/book/assets/js/jquery.min.js"></script>
    <script src="/static/book/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <script src="/static/book/assets/js/theme.js"></script>
</body>

</html>

read/templates/read/basee.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>{% block title %}{% endblock %} - Baca Buku</title>
    <link rel="stylesheet" href="{% static 'baru/style.css' %}">
    {% block head %}
    {% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Baca Buku</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                    <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-link" href="{% url 'read:book-list' %}">List Buku</a>
                    <a class="nav-link" href="/#favorite-book">Buku favorite</a>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    <a class="nav-link  text-success" href="{% url 'account_signup' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

read/templates/read/details.html
{% extends 'read/basee.html' %}

{% block title %}{{book.title}}{% endblock %}

{% block body %}
    <section id="detail" class="mt-5">
      <div class="container">
        <div class="row">
          <div class="col-sm-3">
              <!-- Image here -->
              <img src="{{book.cover.url}}" alt="" class="img-fluid">
              <!-- /images -->
              <!-- Medsos -->

                <div class="d-flex ml-5">

                  <p class="mt-3 pr-3"><i class="fab fa-instagram"></i></p>
                  <p class="mt-3 pr-3"> <i class="fab fa-facebook"></i></p>
                  <p class="mt-3 pr-3"><i class="fab fa-whatsapp"></i></p>
                </div>
              <!-- /Medsos -->
          </div>
          <div class="col-sm-6">
            <h1 class="text-center">{{book.title}}</h1>
            <div class="ml-3 mt-4 ">{{book.description | safe}}</div>
          </div>
          <div class="col-sm-3 w-100 mt-5">
            <h4>Author : </h4>
            <p>{{book.author}}</p>
            <h4>Date : </h4>
            <p>{{book.upload_date | date:" M d, Y - H:i"}}</p>
            <h4>Category:</h4>
            <p>{% for cat in book.category.all %} {{cat}},&nbsp; {% endfor %}</p>
            <h4>Ratings : </h4>
            <div class="d-flex">

              <div class="col" id="rateYo" >

              </div>
              <p class="col">{{book.total_rating}}</p>
            </div>
            {% if user.is_authenticated %}
            <h4>Book Owner : </h4>
            <a class="text-decoration-none text-dark">{{book.uploader}}</a> or <a href="https://wa.me/{{ profile.phone }}">Chat in WhatsApp</a>

            <a href="{{book.book.url}}" target="_blank" class="btn btn-sm mt-4 btn-primary rounded-pill w-100">Baca</a>
            <a href="{{book.book.url}}" download="{{book.book.url}}" class="btn btn-sm mt-2 btn-danger rounded-pill w-100">Download</a>
            {% else %}
            <a href="/accounts/login/?next=/{{ book.get_absolute_url }}" class="btn btn-sm mt-4 btn-primary rounded-pill w-100">Login terlebih dahulu</a>
            {% endif %}
          </div>

        </div>
      </div>
    </section>
    <hr>
    <section id="body" class="mt-5">
      <div class="container">
        {% if not book.comment.all %}
        No Comments Yet.....
        <a href="{% url 'read:add-comment' book.link %}" class="text-italic"> Add One</a>
        {% else %}
        <a href="{% url 'read:add-comment' book.link %}" class="btn btn-primary">Add Comments</a>
        <br><br>
          {% for comment in book.comment.all %}
          <strong>{{comment.name}}</strong>
          <br>
          {{comment.body | safe}}
          <hr>
          {% endfor %}
        {% endif %}
      </div>
    </section>
{% endblock %}

read/templates/read/index.html
{% extends 'read/basee.html' %}
{% load static %}
{% block title %}Literacy Indonesia{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
    <div class="jumbotron bg-primary">
        <div class="container d-flex flex-column align-items-center ">
           <img class="img-fluid" src="{% static 'baru/assets/images/Jumbotron.svg' %}" alt="">
            <h1 class="mt-5 mb-3">Belajar apapun disini melalui buku yang sudah tersedia diwebsite ini.</h1>
            <a class="btn btn-danger w-25 mb-3 ">List Buku</a>
        </div>
    </div>

    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <img class="img-fluid" src="{% static 'baru/assets/images/Asset 1.svg' %}" alt="">
                </div>
                <div class="col-lg-6 caption mt-5 pl-5">
                    <h3 class="pt-3">Gratis E-Books</h3>
                    <p class="text-secondary pt-3">Baca buku gratis seperti buku sekolah dari SD, SMP, SMK atau SMA, buku buku tersebut dibagikan secara gratis untuk menunjang pelajaran kamu supaya lebih giat membaca buku</p>
                    <a href="" class="btn btn-primary mt-3">Explore buku</a>
                </div>
            </div>
        </div>
    </div>

    <div id="favorite-book" class="mt-5 mb-5 bg-primary text-white pt-5 pb-5">
        <h1 class="text-center  font-weight-bold">Favorite Book</h1>
        <p class="text-center">Berikut ini adalah buku favorite yang diambil berdasarkan rating dan jumlah pembacanya </p>
        <div class="container">
            <div class="row">
            {% for book in fav_books %}
                <div class="col-sm-4 mt-5">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{ book.cover.url }}" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text text-dark font-weight-bold">{{ book.title }}</p>
                            <a href="{{ book.get_absolute_url }}" class="text-info">Kunjungi buku</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>

    <div id="search">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1 class="text-primary font-weight-bold">Cari buku </h1>
                    <p class="text-secondary">Cari buku apapun yang kamu suka entah itu komik atau buku pelajaran yang kamu sukai, lalu pelajari buku tersebut secara perlahan lahan sampai buku itu habis kamu baca </p>
                </div>

                <div class="col-sm-6">
                    <form action="" method="post">
                        <div class="input-group " style="margin-top:60px">
                            <input type="text" class="form-control border-0 ">
                        <button type="submit" class="btn btn-primary">Search</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div id="pencapaian" class="bg-primary">
        <div class="container mt-5">
            <div class="d-flex flex-column align-items-center ">
            <h1 class="text-white mt-4">Pencapaian</h1>
            <p class="text-white mt-4 mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam dolorem excepturi eligendi eius maiores nihil fugit voluptate delectus commodi sed! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem, quia fuga maxime ratione veniam reprehenderit ab unde et provident dicta harum rem, cupiditate cumque officia accusamus dolor asperiores. Asperiores, sunt.</p>

            </div>
            <div class="row pb-5">

                <div class="col-lg-4">
                    <div class="card">
                        <img src="{% static 'baru/assets/images/Book.svg' %}" alt="" class="pt-3" height="120">
                        <div class="card-body text-center">
                            <h4>Total Buku</h4>
                            <p>{{ book_total }} Buku</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="card">
                        <img src="{% static 'baru/assets/images/Member.svg' %}" alt="" class="pt-3" height="120">
                        <div class="card-body text-center pb-3">
                            <h4>Total Member</h4>
                            <p>{{ member }} Member</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="card">
                        <img src="{% static 'baru/assets/images/Kategori_1.svg' %}" alt="" class="pt-3" height="120">
                        <div class="card-body text-center">
                            <h4>Total Kategori</h4>
                            <p>{{ category }} kategori</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

read/templates/read/list.html
{% extends 'read/basee.html' %}
{% load static %}
{% block title %}Book List{% endblock %}

{% block head %}
<style href="{% static 'baru/list-buku' %}"></style>
{% endblock %}

{% block body %}
    <div class="jumbotron bg-primary">
        <div class="container">
            <div class="row">
                {% for new in new_book %}
                <div class="col-lg-6 mb-5">
                    <div class="d-flex justify-content-center">
                        <img class="img-fluid " src="{{ new.cover.url }}" alt="">
                    </div>
                </div>

                <div class="col-lg-6">
                    <h1 class="text-white font-weight-bold">{{ new.title }}</h1>
                    <p class="text-white">{{ new.description | safe }}</p>
                    <a href="{% url 'read:detail' new.get_absolute_url %}" class="btn btn-danger">Detail Buku</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="book mb-5">
       <div class="container">
            <div class="card mb-5">
                <div class="card-body">
                    <form method="get" class="input-group ">
                        <input type="text" name="q" class="form-control" placeholder="Cari buku yang anda inginkan disini">
                        <button type="submit" class="btn btn-primary" >Search</button>
                    </form>
                </div>
            </div>


            <div class="row">
              <div class="col-lg-8">

                <div class="row">
                  {% for book in object_list %}
                  <div class="col-lg-4 mt-4">
                    <div class="card border-0">
                      <img src="{{ book.cover.url }}" alt="" class="card-img-top img-fluid">
                      <div class="card-body">
                        <p>{{ book.title }}</p>
                        <a href="{% url 'read:detail' book.get_absolute_url %}" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>

            {% if is_paginated %}=
                <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                    <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Next"><span aria-hidden="true">«</span></a></li>
                    {% endif %}
                        <li class="page-item active"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                    {% endif %}

                    </ul>
                </nav>
            {% endif %}

              </div>
              <div class="col-lg-4">
                <div class="card border-0">

                  <div class="card-body">
                    <h3 class="font-weight-bold ">Favorite book</h3>
                    <hr class="mt-4">
                    {% for fav in fav_books %}
                    <div class="d-flex">
                      <img height="150" class="mt-3"  src="{{ fav.cover.url }}" alt="">
                      <div class="caption ml-3">
                        <p class="font-weight-bold">Siswa handal pelajaran madrasah</p>
                        <p>Dengan ini anda bisa melihat bagaimana sih cara belajar anak madrasah</p>
                        <a href="{% url 'read:detail' fav.get_absolute_url %}" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                    <hr>
                    {% endfor %}

                  </div>
                </div>
              </div>
            </div>



            </div>



        </div>
    </div>


{% endblock %}