backend/urls.py
from django.urls import path
from .views import *

app_name = 'my'

urlpatterns = [
    path('', redirect_check, name='redirect'),
    path('book/', BookListUploaded.as_view(), name='book-list'),
    path('book/check/', upload_check, name='book-check'),
    path('book/upload/', UploadBook.as_view(), name='upload-a-book'),
    path('book/<slug:link>/', BookDetail.as_view(), name='book-detail'),
    path('book/<slug:link>/update', UpdateBook.as_view(), name='book-update'),
]

e_libs/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my/', include('backend.urls', namespace='my')),
    path('profile/', include('members.urls', namespace='profile')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('', include('read.urls', namespace='read')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

read/urls.py
from django.urls import path
from .views import *

app_name = 'read'

urlpatterns = [
    path('', AllBooksList.as_view(), name='book'),
    path('book/', AllBookList.as_view(), name='book-list'),
    # path('<str:cats>/', CategorySearch, name='category'),
    path('<slug:link>/', BookDetailView.as_view(), name='detail'),
    path('<slug:link>/comment/', AddComment.as_view(), name='add-comment'),
]

backend/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    link = models.SlugField(max_length=255, unique=True, default='')
    book = models.FileField(upload_to='book/pdf/')
    cover = models.ImageField(upload_to='book/cover/')
    author = models.CharField(max_length=255)
    availability = models.IntegerField(default=0)
    description = RichTextField(null=True, blank=True, config_name='special')
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    pending = models.BooleanField(default=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    user_rating = models.ManyToManyField(User, related_name='book_rating', blank=True)
    category = models.ManyToManyField(Category)

    def total_rating(self):
        if self.rating == 0 and self.user_rating.count() == 0:
            return self.rating
        else:
            a = int(self.rating)
            b = self.user_rating.count()
            c = a / int(b)
            return c

    def current_rate(self):
        return int(self.rating)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.book.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return self.link

backend/forms.py
from django import forms
from .models import Book, Category

category_choices = Category.objects.all().values_list("id", "name")

category_list = []

for category in category_choices:
    category_list.append(category)


class UploadBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'book', 'cover', 'author', 'availability', 'description', 'category')

        widgets = {
            'category': forms.CheckboxSelectMultiple(choices=category_list)
        }


class UpdateUploadedBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'availability', 'description', 'category')

        widgets = {
            'category': forms.CheckboxSelectMultiple(choices=category_list)
        }

backend/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import *
from .models import Book
from .forms import UploadBookForm, UpdateUploadedBook
from django.db.models import Q as __
import os
from django.conf import settings
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from members.models import UserProfile
from .utils import staff_required

link = 'link'


@staff_required
def upload_check(request):
    profile_ = UserProfile.objects.filter(user_id=request.user.id)
    # print(profile_)
    if not profile_:
        # if user had create their profile
        return redirect('profile:create-profile')
    else:
        # if not create
        return redirect('my:upload-a-book')


def redirect_check(request):
    book = Book.objects.filter(uploader_id=request.user.id).count()
    if book != 0:
        return redirect('my:book-list')
    else:
        return redirect('my:book-check')


class BookListUploaded(ListView):
    model = Book
    template_name = 'book-list.html'
    paginate_by = 10
    ordering = ['-id']

    def get_queryset(self):
        qq = self.request.GET.get('q')
        book_total = Book.objects.filter(uploader=self.request.user.id).count()

        if book_total != 0:
            if qq is not None:
                object_list = Book.objects.filter(
                    __(title__icontains=qq) | __(author__icontains=qq) |
                    __(description__icontains=qq) | __(link__icontains=qq)
                )
                object_list.filter(uploader=self.request.user.id)
            else:
                object_list = Book.objects.filter(uploader=self.request.user.id)
        else:
            return HttpResponseRedirect(reverse('my:book-check'))

        return object_list

    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BookListUploaded, self).dispatch(request, *args, **kwargs)


class BookDetail(DetailView):
    model = Book
    template_name = 'book-detail.html'
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link

    def get_context_data(self, *args, **kwargs):
        context = super(BookDetail, self).get_context_data(*args, **kwargs)

        return context

    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BookDetail, self).dispatch(request, *args, **kwargs)


@staff_required
def download(req, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type='application/file')
            response['Content-Dispotition'] = 'inline;filenam=' + os.path.basename(file_path)
            return response
    raise Http404


class UploadBook(CreateView):
    model = Book
    form_class = UploadBookForm
    template_name = 'upload.html'
    success_url = reverse_lazy('my:book-list')

    def form_valid(self, form):
        form.instance.uploader_id = self.request.user.id
        link_ = str(self.request.POST.get('title'))
        str_id = str(self.request.user.id)
        link_ = str_id + '_' + link_
        link_ = link_.replace(" ", "-")
        form.instance.link = link_

        return super(UploadBook, self).form_valid(form) and HttpResponseRedirect(self.get_success_url())

    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UploadBook, self).dispatch(request, *args, **kwargs)
    
    
class UpdateBook(UpdateView):
    model = Book
    form_class = UpdateUploadedBook
    template_name = 'update.html'
    success_url = reverse_lazy('my:book-list')
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link

    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UpdateBook, self).dispatch(request, *args, **kwargs)

backend/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/book/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="/static/book/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    {% block head %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-white portfolio-navbar gradient">
        <div class="container"><a class="navbar-brand logo" href="/my/book/">E Libs</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navbarNav"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="projects-grid-cards.html">Projects</a></li>
                    <li class="nav-item"><a class="nav-link active" href="project-page.html">Project Page</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <main class="page project-page">
        {% block body %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="container">
            <div class="links"><a href="#">About me</a><a href="#">Contact me</a><a href="#">Projects</a></div>
            <div class="social-icons"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-instagram-outline"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a></div>
        </div>
    </footer>
    <script src="/static/book/assets/js/jquery.min.js"></script>
    <script src="/static/book/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <script src="/static/book/assets/js/theme.js"></script>
</body>

</html>

backend/templates/book-detail.html
{% extends 'base.html' %}

{% block title %}
Book | {{book.title}}
{% endblock %}

{% block body %}
        <section class="portfolio-block project">
            <div class="container">
                <div class="heading">
                    <h2>{{book.title}}</h2>
                </div>
                <img src="{{book.cover.url}}" alt="Book Cover" class="image img-fluid" style="height: 100%;">
                <div class="row">
                    <div class="col-12 col-md-6 offset-md-1 info">
                        <h3>Description</h3>
                        {{book.description | safe}}
                        <hr>
                        <h3>Category</h3>
                        <p>{% for cat in book.category.all %} {{cat}},&nbsp;{% endfor %}</p>
                    </div>
                    <div class="col-12 col-md-3 offset-md-1 meta">
                        <div class="tags">
                            <span class="meta-heading">Author</span>
                            <a href="#">{{book.author}}</a>
                            <span class="meta-heading">Date</span>
                            <span>{{book.upload_date | date:" M d, Y - H:i"}}</span>
                            <span class="meta-heading">Rating</span>
                            <span>{{book.total_rating}}</span>
                            <span><a href="{% url 'my:book-update' book.link %}" class="btn text-white btn-primary">Update This Book Data</a></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-6 offset-md-1 info">
                        <h3>Read This Book or Download PDF</h3>
                        <a href="{{book.book.url}}" target="_blank" class="btn btn-lg btn-primary">{{book.title}}</a>

                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-6 offset-md-1 mt-3">
                        <a href="{{book.book.url}}" download="{{book.book.url}}" class="btn btn-primary">Download</a>
                    </div>
                </div>

            </div>
        </section>
{% endblock %}

backend/templates/book-list.html
{% extends 'base.html' %}

{% block title %}
My Uploaded Books
{% endblock %}

{% block body %}
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-nowrap"></div>
                    <div class="col-md-6 mt-5">
                        <div class="text-md-right dataTables_filter" id="dataTable_filter">
                            <form class="border-right-0 d-none d-sm-inline-block mr-auto my-2 my-md-0 mw-100 navbar-search justify-content-end">
                                <div class="input-group"><input class="form-control small" type="text" name="q" placeholder="Search for ...">
                                    <div class="input-group-append"><button class="btn btn-primary py-0 rounded-right" type="button">&#8594;</button></div>
                                 </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="portfolio-block projects-cards">
            <div class="container">
                <div class="heading">
                    <h2>My Uploaded Books</h2>
                </div>
                <div class="row">
                    {% for book in object_list %}
                    <div class="col-md-6 col-lg-4">
                        <div class="card border-0">
                            <a href="{% url 'my:book-detail' book.link %}"><img class="card-img-top scale-on-hover" src="{{book.cover.url}}" alt="Card Image"></a>
                            <div class="card-body">
                                <h6><a href="{% url 'my:book-detail' book.link %}">{{book.title}}</a></h6>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

<div class="jumbotron bg-primary">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5">
                    <div class="d-flex justify-content-center">
                     <img class="img-fluid " src="assets/images/bahasasunda.jpg" alt="">

                    </div>
                </div>
                <div class="col-lg-6">

                    <h1 class="text-white font-weight-bold">Kamus bahasa sunda</h1>
                    <p class="text-white">Buku ini sangat cocok untuk anda jika mau belajar bahasa sunda, dengan bahasan yang menarik sehingga anda menjadi lebih paham bahasa sunda dan juga lebih mendalami bahasa sunda</p>
                    <a href="" class="btn btn-danger   ">Detail Buku</a>
                </div>
            </div>
        </div>


    </div>
    <div class="book">
       <div class="container">
         <div class="card mb-5">
           <div class="card-body">
            <div class="input-group ">
              <input type="text" class="form-control" placeholder="Cari buku yang anda inginkan disini">
              <button type="submit" class="btn btn-primary" >Search</button>
            </div>
           </div>
         </div>


            <div class="row">
              <div class="col-lg-8">
                <ul class="nav nav-pills nav-fill">
                  <li class="nav-item">
                  <a class="nav-link active" href="#">Edukasi</a>
                  </li>
                  <li class="nav-item">
                  <a class="nav-link" href="#">Kesehatan</a>
                  </li>
                  <li class="nav-item">
                  <a class="nav-link" href="#">Ekonomi</a>
                  </li>


              </ul>

                <div class="row mt-5">
                  <div class="col-lg-4 mt-4">
                    <div class="card border-0">
                      <img src="assets/images/pengingkatan_prestasi_belajar.jpg" alt="" class="card-img-top img-fluid">
                      <div class="card-body">
                        <p>Peningkatan cara belajar siswa mengenai agama</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 mt-4">
                    <div class="card border-0">
                      <img src="assets/images/pengingkatan_prestasi_belajar.jpg" alt="" class="card-img-top img-fluid">
                      <div class="card-body">
                        <p>Peningkatan cara belajar siswa mengenai agama</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 mt-4">
                    <div class="card border-0">
                      <img src="assets/images/pengingkatan_prestasi_belajar.jpg" alt="" class="card-img-top img-fluid">
                      <div class="card-body">
                        <p>Peningkatan cara belajar siswa mengenai agama</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 mt-4">
                    <div class="card border-0">
                      <img src="assets/images/pengingkatan_prestasi_belajar.jpg" alt="" class="card-img-top img-fluid">
                      <div class="card-body">
                        <p>Peningkatan cara belajar siswa mengenai agama</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 mt-4">
                    <div class="card border-0">
                      <img src="assets/images/pengingkatan_prestasi_belajar.jpg" alt="" class="card-img-top img-fluid">
                      <div class="card-body">
                        <p>Peningkatan cara belajar siswa mengenai agama</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 mt-4">
                    <div class="card border-0">
                      <img src="assets/images/pengingkatan_prestasi_belajar.jpg" alt="" class="card-img-top img-fluid">
                      <div class="card-body">
                        <p>Peningkatan cara belajar siswa mengenai agama</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                  </div>



                </div>

                   <nav aria-label="Page navigation example" class="mt-3">

                  <ul class="pagination">
                    <li class="page-item">
                      <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">4</a></li>
                    <li class="page-item"><a class="page-link" href="#">5</a></li>
                    <li class="page-item"><a class="page-link" href="#">6</a></li>
                    <li class="page-item">
                      <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                  </ul>
                </nav>

              </div>
              <div class="col-lg-4">
                <div class="card border-0">

                  <div class="card-body">
                    <h3 class="font-weight-bold ">Favorite book</h3>
                    <hr class="mt-4">
                    <div class="d-flex">
                      <img height="150" class="mt-3"  src="assets/images/salam.jpg" alt="">
                      <div class="caption ml-3">
                        <p class="font-weight-bold">Siswa handal pelajaran madrasah</p>
                        <p>Dengan ini anda bisa melihat bagaimana sih cara belajar anak madrasah</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                    <hr>
                    <div class="d-flex">
                      <img height="150" class="mt-3"  src="assets/images/salam.jpg" alt="">
                      <div class="caption ml-3">
                        <p class="font-weight-bold">Siswa handal pelajaran madrasah</p>
                        <p>Dengan ini anda bisa melihat bagaimana sih cara belajar anak madrasah</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                    <hr>
                    <div class="d-flex">
                      <img height="150" class="mt-3"  src="assets/images/salam.jpg" alt="">
                      <div class="caption ml-3">
                        <p class="font-weight-bold">Siswa handal pelajaran madrasah</p>
                        <p>Dengan ini anda bisa melihat bagaimana sih cara belajar anak madrasah</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                    <hr>
                    <div class="d-flex">
                      <img height="150" class="mt-3"  src="assets/images/salam.jpg" alt="">
                      <div class="caption ml-3">
                        <p class="font-weight-bold">Siswa handal pelajaran madrasah</p>
                        <p>Dengan ini anda bisa melihat bagaimana sih cara belajar anak madrasah</p>
                        <a href="" class="text-primary">Lihat buku</a>
                      </div>
                    </div>
                    <hr>




                  </div>
                </div>
              </div>
            </div>



            </div>



        </div>
    </div>
    <div class="favorite mb-5">
      <div class="container">
        <h1 class="mt-4">Author terfavorite</h1>
        <div class="row">
          <div class="col-sm-4 mt-5">
            <div class="card">
              <img height="400" src="assets/images/pasti-pintar.jpg" alt="" class="card-img-top">
              <div class="card-body">
                <p class="font-weight-bold">Pasti pintar disetiap mata pelajaran</p>
                <a href="" class="text-primary">Lihat buku</a>
              </div>
            </div>

          </div>
          <div class="col-sm-4 mt-5">
            <div class="card">
              <img height="400" src="assets/images/pasti-pintar.jpg" alt="" class="card-img-top">
              <div class="card-body">
                <p class="font-weight-bold">Pasti pintar disetiap mata pelajaran</p>
                <a href="" class="text-primary">Lihat buku</a>
              </div>
            </div>

          </div>
          <div class="col-sm-4 mt-5">
            <div class="card">
              <img height="400" src="assets/images/pasti-pintar.jpg" alt="" class="card-img-top">
              <div class="card-body">
                <p class="font-weight-bold">Pasti pintar disetiap mata pelajaran</p>
                <a href="" class="text-primary">Lihat buku</a>
              </div>
            </div>

          </div>


        </div>
      </div>
    </div>
{% endblock %}

backend/templates/update.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>{% block title %}My Site{% endblock %}</title>
    <style>
        body {
              background-color: #5c848e;
        }
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#decdc3">
    <div class="container">
      <a class="navbar-brand" href="#">My Site</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Simple Upload</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Model Forms Upload</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Model Forms Upload (CBV)</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            <h2>Upload book</h2>
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                {{ form.media }}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary">Upload book</button>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

backend/templates/upload.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>{% block title %}My Site{% endblock %}</title>
    <style>
        body {
              background-color: #5c848e;
        }
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#decdc3">
    <div class="container">
      <a class="navbar-brand" href="#">My Site</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Simple Upload</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Model Forms Upload</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Model Forms Upload (CBV)</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            <h2>Upload book</h2>
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                {{ form.media }}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary"> Update </button>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>